version: "3.9"

services:
  web:
    build: .
    container_name: cnbc_monitor_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./media:/app/media
    environment:
      - DJANGO_SETTINGS_MODULE=cnbc_monitor.settings
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
